# Copyright: 2025 Roberto Calabrese a.k.a. Kicka
#
# This file is part of "Mustang", a GUI toolkit for Tcl/Tk 9.0 and later
# (https://github.com/robertocalabrese/Mustang).
#
# The author hereby grant permission to use, copy, modify, distribute,
# and license this software and its documentation for any purpose, provided
# that existing copyright notices are retained in all copies and that this
# notice is included verbatim in any distributions. No written agreement,
# license, or royalty fee is required for any of the authorized uses.
# Modifications to this software may be copyrighted by their authors
# and need not follow the licensing terms described here, provided that
# the new terms are clearly indicated on the first page of each file where
# they apply.
#
# IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY
# DERIVATIVES THEREOF, EVEN IF THE AUTHOR HAVE BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# THE AUTHOR AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.  THIS SOFTWARE
# IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHOR AND DISTRIBUTORS HAVE
# NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR
# MODIFICATIONS.
#
# GOVERNMENT USE: If you are acquiring this software on behalf of the
# U.S. government, the Government shall have only "Restricted Rights"
# in the software and related documentation as defined in the Federal
# Acquisition Regulations (FARs) in Clause 52.227.19 (c) (2).  If you
# are acquiring the software on behalf of the Department of Defense, the
# software shall be classified as "Commercial Computer Software" and the
# Government shall have only "Restricted Rights" as defined in Clause
# 252.227-7013 (c) (1) of DFARs.  Notwithstanding the foregoing, the
# author grant the U.S. Government and others acting in its behalf
# permission to use and distribute the software in accordance with the
# terms specified in this license.

namespace eval ::ms {
    # Errors
    ::msgcat::mcset  en "Operating system not supported."
    ::msgcat::mcset  en "Missing colors."
    ::msgcat::mcset  en "Missing themes."
    ::msgcat::mcset  en "Quit the application."

    # Buttons
    ::msgcat::mcset  en "abort"
    ::msgcat::mcset  en "about"
    ::msgcat::mcset  en "apply"
    ::msgcat::mcset  en "back"
    ::msgcat::mcset  en "cancel"
    ::msgcat::mcset  en "close"
    ::msgcat::mcset  en "continue"
    ::msgcat::mcset  en "copy"
    ::msgcat::mcset  en "cut"
    ::msgcat::mcset  en "delete"
    ::msgcat::mcset  en "edit"
    ::msgcat::mcset  en "exit"
    ::msgcat::mcset  en "help"
    ::msgcat::mcset  en "ignore"
    ::msgcat::mcset  en "no"
    ::msgcat::mcset  en "ok"
    ::msgcat::mcset  en "open"
    ::msgcat::mcset  en "paste"
    ::msgcat::mcset  en "quit"
    ::msgcat::mcset  en "retry"
    ::msgcat::mcset  en "save"
    ::msgcat::mcset  en "yes"
}

#*EOF*