# Copyright: 2025 Roberto Calabrese a.k.a. Kicka
#
# This file is part of "Mustang", a GUI toolkit for Tcl/Tk 9.0 and later
# (https://github.com/robertocalabrese/Mustang).
#
# The author hereby grant permission to use, copy, modify, distribute,
# and license this software and its documentation for any purpose, provided
# that existing copyright notices are retained in all copies and that this
# notice is included verbatim in any distributions. No written agreement,
# license, or royalty fee is required for any of the authorized uses.
# Modifications to this software may be copyrighted by their authors
# and need not follow the licensing terms described here, provided that
# the new terms are clearly indicated on the first page of each file where
# they apply.
#
# IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY
# DERIVATIVES THEREOF, EVEN IF THE AUTHOR HAVE BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# THE AUTHOR AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.  THIS SOFTWARE
# IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHOR AND DISTRIBUTORS HAVE
# NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR
# MODIFICATIONS.
#
# GOVERNMENT USE: If you are acquiring this software on behalf of the
# U.S. government, the Government shall have only "Restricted Rights"
# in the software and related documentation as defined in the Federal
# Acquisition Regulations (FARs) in Clause 52.227.19 (c) (2).  If you
# are acquiring the software on behalf of the Department of Defense, the
# software shall be classified as "Commercial Computer Software" and the
# Government shall have only "Restricted Rights" as defined in Clause
# 252.227-7013 (c) (1) of DFARs.  Notwithstanding the foregoing, the
# author grant the U.S. Government and others acting in its behalf
# permission to use and distribute the software in accordance with the
# terms specified in this license.

namespace eval ::ms {
    # Errors
    ::msgcat::mcset  zh_cn "Operating system not supported." "不支持作系统。"

    # Buttons
    ::msgcat::mcset  zh_cn "abort" "中止"
    ::msgcat::mcset  zh_cn "about" "关于"
    ::msgcat::mcset  zh_cn "apply" "应用"
    ::msgcat::mcset  zh_cn "back" "返回"
    ::msgcat::mcset  zh_cn "cancel" "取消"
    ::msgcat::mcset  zh_cn "close" "关闭"
    ::msgcat::mcset  zh_cn "continue" "继续"
    ::msgcat::mcset  zh_cn "copy" "复制"
    ::msgcat::mcset  zh_cn "cut" "剪切"
    ::msgcat::mcset  zh_cn "delete" "删除"
    ::msgcat::mcset  zh_cn "edit" "编辑"
    ::msgcat::mcset  zh_cn "exit" "退出"
    ::msgcat::mcset  zh_cn "help" "帮助"
    ::msgcat::mcset  zh_cn "ignore" "忽视"
    ::msgcat::mcset  zh_cn "no" "不"
    ::msgcat::mcset  zh_cn "ok" "还行"
    ::msgcat::mcset  zh_cn "open" "打开"
    ::msgcat::mcset  zh_cn "paste" "粘贴"
    ::msgcat::mcset  zh_cn "quit" "退出"
    ::msgcat::mcset  zh_cn "retry" "重试"
    ::msgcat::mcset  zh_cn "save" "救"
    ::msgcat::mcset  zh_cn "yes" "确定"
}

#*EOF*